# -*- coding: utf-8 -*-
"""IA2.5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3TzwiOLYzcyq5xeVU7iqjFZ80YvUSeH
"""

import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.frequent_patterns import apriori as mlxtend_apriori
from sklearn.preprocessing import StandardScaler, LabelEncoder
from mlxtend.preprocessing import TransactionEncoder

# Section 1: Data Collection
transactions_df = pd.read_csv('Groceries_dataset.csv')
print("Section 1: Data Collection")
print("=" * 50)
print("Displaying the first 10 rows of the raw data:")
print(transactions_df.head(10).to_string(index=False))

# Section 2: Data Preprocessing
transactions_df.columns = transactions_df.columns.str.lower().str.strip()
print("Section 2: Data Preprocessing (standardize column names and remove duplicates)")
list(transactions_df.columns)

# Removes Duplicates
transactions_df.drop_duplicates(inplace=True)
transactions_df.reset_index(drop=True, inplace= True)
print("Removed Duplicates:")
transactions_df

grouped = transactions_df.groupby('member_number')['itemdescription']
grouped_list = grouped.agg(list).reset_index()
print("Grouped Transactions:")
grouped_list

transactions_list = grouped_list['itemdescription'].tolist()
print(f"Total transactions prepared: {len(transactions_list)}")
transactions_list[:5]

te = TransactionEncoder()
te_array = te.fit(transactions_list).transform(transactions_list)
df_encoded = pd.DataFrame(te_array, columns=te.columns_)
df_encoded

print("Section 3: Apriori (mlxtend)")

min_support = 0.003
min_confidence = 0.5
min_lift = 3
min_length = 1
max_length = 4

try:
    df_encoded
except NameError:
    raise NameError("df_encoded not found. Run the one-hot encoding block (Section 2b) first.")

frequent_itemsets = mlxtend_apriori(df_encoded, min_support=min_support, use_colnames=True)

frequent_itemsets['itemset_len'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

frequent_itemsets = frequent_itemsets[
    (frequent_itemsets['itemset_len'] >= min_length) &
    (frequent_itemsets['itemset_len'] <= max_length)
].reset_index(drop=True)

if frequent_itemsets.empty:
    print("No frequent itemsets found for min_support =", min_support)
    rules_df = pd.DataFrame(columns=["antecedents","consequents","support","confidence","lift"])
else:
    rules_df = association_rules(frequent_itemsets, metric="confidence", min_threshold=min_confidence)
    rules_df['antecedent_len'] = rules_df['antecedents'].apply(lambda x: len(x))
    rules_df['consequent_len'] = rules_df['consequents'].apply(lambda x: len(x))
    rules_df = rules_df[
        (rules_df['lift'] >= min_lift) &
        (rules_df['antecedent_len'] >= min_length) &
        (rules_df['antecedent_len'] <= max_length)
    ].reset_index(drop=True)

def inspect_mlxtend(rules):
    if rules.empty:
        return []
    lhs = rules["antecedents"].apply(lambda x: tuple(sorted(x))).tolist()
    rhs = rules["consequents"].apply(lambda x: tuple(sorted(x))).tolist()
    support = rules["support"].tolist()
    confidence = rules["confidence"].tolist()
    lift = rules["lift"].tolist()
    return list(zip(lhs, rhs, support, confidence, lift))

result_df = pd.DataFrame(inspect_mlxtend(rules_df),
                         columns=["left_hand_side", "right_hand_side", "support", "confidence", "lift"])
result_df = result_df.sort_values(by="lift", ascending=False).reset_index(drop=True)

display(result_df)

# Section 6: Bar chart - Top 10 Most Purchased Items
import matplotlib.pyplot as plt
from collections import Counter

all_items = [item for tx in transactions_list for item in tx]
item_counts = Counter(all_items)
top10 = item_counts.most_common(10)
top10_df = pd.DataFrame(top10, columns=['item','count'])

plt.figure(figsize=(10,6))
plt.bar(top10_df['item'], top10_df['count'])
plt.xticks(rotation=45, ha='right')
plt.ylabel('Count')
plt.title('Top 10 Most Purchased Items')
plt.tight_layout()
plt.show()

plt.savefig('section6_top10_items.png', bbox_inches='tight')

# Section 7: Bar chart - Top 10 Item Combinations (pairs) by support
from itertools import combinations

pair_counts = Counter()
for tx in transactions_list:
    unique_items = sorted(set(tx))
    for a,b in combinations(unique_items, 2):
        pair_counts[(a,b)] += 1

n_tx = len(transactions_list)
pairs_df = pd.DataFrame([
    {'itemA': a, 'itemB': b, 'count': cnt, 'support': cnt / n_tx}
    for (a,b), cnt in pair_counts.items()
])
pairs_df = pairs_df.sort_values('support', ascending=False).reset_index(drop=True)
top10_pairs = pairs_df.head(10).copy()
top10_pairs['pair_str'] = top10_pairs['itemA'] + ', ' + top10_pairs['itemB']

plt.figure(figsize=(10,6))
plt.bar(top10_pairs['pair_str'], top10_pairs['support'])
plt.xticks(rotation=45, ha='right')
plt.ylabel('Support')
plt.title('Top 10 Item Pairs by Support')
plt.tight_layout()
plt.show()

plt.savefig('section7_top10_itempairs.png', bbox_inches='tight')

# Section 8: Scatter plot - Support vs Confidence for rules found by apyori

if 'result_df' not in globals():
    raise RuntimeError("result_df not found. Run Section 3 (Apriori) first.")

plt.figure(figsize=(8,6))
plt.scatter(result_df['support'], result_df['confidence'])
plt.xlabel('Support')
plt.ylabel('Confidence')
plt.title('Association Rules: Support vs Confidence')
plt.grid(True)

try:
    top5 = result_df.sort_values('lift', ascending=False).head(5)
    for _, row in top5.iterrows():
        lhs = ','.join(row['left_hand_side']) if isinstance(row['left_hand_side'], (list, tuple)) else str(row['left_hand_side'])
        rhs = ','.join(row['right_hand_side']) if isinstance(row['right_hand_side'], (list, tuple)) else str(row['right_hand_side'])
        label = f"{lhs} -> {rhs}\nlift={row['lift']:.2f}"
        plt.annotate(label, (row['support'], row['confidence']), textcoords="offset points", xytext=(5,-10), fontsize=8)
except Exception as e:
    print("Annotate skipped:", e)

plt.tight_layout()
plt.show()

plt.savefig('section8_support_vs_confidence.png', bbox_inches='tight')

# Section 9: Scatter plot - Confidence vs Lift for rules found by apyori
import matplotlib.pyplot as plt

if 'result_df' not in globals():
    raise RuntimeError("rResult_df not found. Run Section 3 (Apriori) first.")

plt.figure(figsize=(8,6))
plt.scatter(result_df['confidence'], result_df['lift'])
plt.xlabel('Confidence')
plt.ylabel('Lift')
plt.title('Association Rules: Confidence vs Lift')
plt.grid(True)

try:
    top5_lift = result_df.sort_values('lift', ascending=False).head(5)
    for _, row in top5_lift.iterrows():
        lhs = ','.join(row['left_hand_side']) if isinstance(row['left_hand_side'], (list, tuple)) else str(row['left_hand_side'])
        rhs = ','.join(row['right_hand_side']) if isinstance(row['right_hand_side'], (list, tuple)) else str(row['right_hand_side'])
        label = f"{lhs} -> {rhs}\nlift={row['lift']:.2f}"
        plt.annotate(label, (row['confidence'], row['lift']), textcoords="offset points", xytext=(5,-10), fontsize=8)
except Exception as e:
    print("Annotate skipped:", e)

plt.tight_layout()
plt.show()

plt.savefig('section9_confidence_vs_lift.png', bbox_inches='tight')

# Section 10: Heatmap - Item Co-occurrence (top N items)
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
from itertools import combinations

if 'transactions_list' not in globals():
    raise RuntimeError("transactions_list not found. Run Section 2 (preprocessing) first.")

TOP_N = 20
all_items = [item for tx in transactions_list for item in tx]
item_counts = Counter(all_items)
top_items = [it for it,_ in item_counts.most_common(TOP_N)]

idx = {it:i for i,it in enumerate(top_items)}
mat = np.zeros((len(top_items), len(top_items)), dtype=int)

for tx in transactions_list:
    items = set(tx) & set(top_items)
    for a,b in combinations(items, 2):
        i,j = idx[a], idx[b]
        mat[i,j] += 1
        mat[j,i] += 1

for it,i in idx.items():
    mat[i,i] = item_counts[it]

plt.figure(figsize=(12,10))
plt.imshow(mat, interpolation='nearest', aspect='auto')
plt.colorbar()
plt.xticks(ticks=np.arange(len(top_items)), labels=top_items, rotation=90)
plt.yticks(ticks=np.arange(len(top_items)), labels=top_items)
plt.title(f'Item Co-occurrence Heatmap (top {len(top_items)} items)')
plt.tight_layout()
plt.show()

plt.savefig('section10_item_cooccurrence_heatmap.png', bbox_inches='tight')